import {chart} from './chart.js';
import {createApp,h,ref,onMounted,onUnmounted,watch,nextTick} from './vue.js';
const fmt=(n,d=2)=>n==null?'—':Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const money=n=>n==null?'—':`${n>=0?'+':'−'}$${fmt(Math.abs(n))}`;
const time=t=>t?new Date(t).toLocaleTimeString('en-GB',{timeZone:'America/New_York',hour12:false}):'—';
const states={STOPPED:'尚未启动',CONNECTING:'正在连接',WAITING_PERMISSION:'等待行情权限',WAITING_CASH_SESSION:'等待现金开盘',OBSERVING:'正在观察',PAUSED:'暂停新入场',DATA_BLOCKED:'数据异常',ERROR:'运行已停止',RECOVERY_REQUIRED:'需要核对上次持仓'};
const reasons={STOP:'止损',TARGET:'达到目标',RTH_CLOSE:'现金收盘',UNOBSERVED_PRICE_PATH:'报价路径缺失',DATA_FAILURE:'数据中断',LATE_START_PAUSED_OR_LATE_SIGNAL:'迟到或暂停，跳过入场',ENTRY_BEYOND_STOP:'开盘已越过止损',MISSING_FRESH_CLOSE_QUOTE:'缺少收盘新鲜报价'};
const kinds={SIGNAL:'突破确认',ENTRY_PROXY:'模拟入场',EXIT_PROXY:'模拟平仓',ENTRY_SKIPPED:'跳过入场',POSITION_INVALIDATED:'观察无效',QUOTE_GAP:'报价缺口',DATA_BLOCKED:'数据异常',SESSION:'开始当日观察',REGISTER:'冻结运行参数',PAUSE_NEW_ENTRIES:'暂停新入场',RESUME_NEW_ENTRIES:'继续观察',DAILY_REPORT:'每日总结已保存',USER_OPTIMIZATION_CHOICE:'已记录优化选择',ERROR:'运行异常'};
const errors={CHECK_MARKET_PERMISSIONS_FIRST:'报价与历史1m权限需检查通过。',RECHECK_PERMISSIONS_REQUIRED:'请重新检查权限，检查已超过十分钟。',FUTURES_PERMISSION_DENIED:'OpenD 返回无行情权限，请核对 CME 授权及登录。',FUTURES_REQUEST_FAILED:'行情请求未完成，请检查 OpenD 连接。',ALREADY_RUNNING:'观察程序已在运行。',UNRESOLVED_PREVIOUS_OBSERVATION:'上次模拟持仓未完成，请核对日志。',COSTS_INVALID:'请填写有效费用和整数滑点。'};
const title=(text,extra=[])=>h('div',{class:'section-head'},[h('h2',text),...extra]);
const pill=(text,cls='')=>h('span',{class:`pill ${cls}`},text);
const empty=(heading,description)=>h('div',{class:'empty'},[h('div',{class:'empty-icon'},'↗'),h('h3',heading),h('p',description)]);
const button=(label,fn,cls='',disabled=false)=>h('button',{onClick:fn,class:cls,disabled},label);
createApp({setup(){
 const data=ref(null),connected=ref(false),page=ref('desk'),settings=ref(false),date=ref(''),interval=ref(1),selected=ref(null),message=ref(''),busy=ref(false);
 const form=ref({product:'ES',contract:'US.ES2612',expires_on:'',timezone:'America/New_York',fee:'',slip:''});const clock=ref(Date.now());let token='',stream,timer;
 function connect(){stream?.close();connected.value=false;stream=new EventSource('/api/stream'+(date.value?'?date='+date.value:''));stream.onmessage=e=>{data.value=JSON.parse(e.data);connected.value=true;};stream.onerror=()=>{connected.value=false;};}
 async function act(action,values={}){busy.value=true;try{const r=await fetch('/action',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify({action,...values})});const result=await r.json();if(!r.ok)throw new Error(result.error||'请检查表单输入');message.value=action==='choose'?'优化意向已记录；策略尚未改动。':'操作已接收';if(action==='start')settings.value=false;}catch(e){message.value=errors[e.message]||e.message;}finally{busy.value=false;}}
 watch(settings,async value=>{await nextTick();if(value)document.querySelector('.settings button')?.focus();});
 function start(e){e.preventDefault();act('start',{...form.value,fee:Number(form.value.fee),slip:Number(form.value.slip)});}
 onMounted(async()=>{timer=setInterval(()=>clock.value=Date.now(),1000);try{token=(await (await fetch('/session')).json()).token;connect();}catch(e){message.value='无法连接本机服务，请重新启动控制台。';}});onUnmounted(()=>{stream?.close();clearInterval(timer);});
 function tradeTable(v,full=false){const columns=full?['时间 ET','合约 / 方向','入场','出场','止损 / 目标','费用 / 滑点','净盈亏 USD','状态']:['入场时间 ET','方向','入场 → 出场','净盈亏 USD','状态'];const select=t=>{selected.value=t.id;page.value='desk';};return h('div',{class:'table-wrap'},[h('table',[h('thead',[h('tr',columns.map(c=>h('th',c)))]),h('tbody',v.trades.length?v.trades.map(t=>h('tr',{class:selected.value===t.id?'selected':'',tabindex:0,onClick:()=>select(t),onKeydown:e=>{if(e.key==='Enter')select(t);}},full?[h('td',time(t.entry_time)),h('td',`${t.contract||'未记录'} · ${t.direction===1?'多':'空'} ${t.quantity??'—'}合约`),h('td',fmt(t.entry_price)),h('td',fmt(t.exit_price)),h('td',`${fmt(t.stop)} / ${fmt(t.target)}`),h('td',`${fmt(t.fee_usd)} USD / ${t.slippage_ticks??'—'} tick`),h('td',{class:t.net_usd>=0?'positive':'negative'},money(t.net_usd)),h('td',pill(t.status==='COMPLETE'?'已平仓':t.status==='INVALID'?'数据无效':'持仓中'))]:[h('td',time(t.entry_time)),h('td',t.direction===1?'做多':'做空'),h('td',`${fmt(t.entry_price)} → ${fmt(t.exit_price)}`),h('td',{class:t.net_usd>=0?'positive':'negative'},money(t.net_usd)),h('td',t.status==='COMPLETE'?'已平仓':t.status==='INVALID'?'数据无效':'持仓中')])):[h('tr',[h('td',{colspan:columns.length,class:'no-trades'},'尚无模拟交易。信号与数据检查通过后才入场。')])])])]);}
 function field(label,key,options=null,type='text',hint=''){return h('label',{class:'field'},[h('span',label),options?h('select',{value:form.value[key],onChange:e=>{form.value[key]=e.target.value;if(key==='product'){const code=data.value?.permissions.products?.[e.target.value]?.sample_contract;if(code)form.value.contract=code;}}},options.map(([v,t])=>h('option',{value:v},t))):h('input',{type,value:form.value[key],required:true,min:type==='number'?0:undefined,step:key==='slip'?'1':type==='number'?'0.01':undefined,max:key==='slip'?20:undefined,onInput:e=>form.value[key]=e.target.value}),hint?h('small',hint):null]);}
 return()=>{
 const s=data.value,f=s?.forward||{},v=s?.view||{trades:[],bars:[],markers:[],events:[],dates:[],quote:{},metrics:{}},q={...v.quote},m={...v.metrics},viewTrade=v.trades.find(t=>t.id===selected.value),historical=v.date&&v.date!==v.today;
 if(q.age_seconds!=null&&v.server_time_utc)q.age_seconds+=Math.max(0,(clock.value-new Date(v.server_time_utc).getTime())/1000);
 q.stale=q.stale||!connected.value||q.age_seconds>10;if(q.stale)m.unrealized_gross_usd=null;
 const permission=s?.permissions.products?.[form.value.product],gate=permission?.snapshot&&permission?.history;
 const stats=[[historical?'当日最后报价':'最新价格',fmt(q.price),'实际月份合约'],['已实现净盈亏',money(m.realized_net_usd),'扣声明的往返费用'],['持仓浮盈',money(m.unrealized_gross_usd),q.stale?'报价过期，暂停估值':'未扣未实现费用'],['当日交易',`${m.completed??0} / ${m.entries??0}`,'已完成 / 已入场']];const panels=[];
 if(page.value==='desk')panels.push(h('div',{class:'desk-grid'},[
 h('section',{class:'panel chart-panel'},[title('行情与买卖点',[h('div',{class:'segmented'},[1,5].map(n=>button(`${n} 分钟`,()=>interval.value=n,interval.value===n?'active':'')))]),chart(v,interval.value,selected.value,id=>selected.value=id),h('p',{class:'muted chart-caption'},'纽约 ET · 仅完成 K 线 · 点击买卖点查看交易详情')]),
 h('section',{class:'panel position-panel'},[title('当前模拟持仓'),v.position?[pill(v.position.direction===1?'做多 · 1 合约':'做空 · 1 合约','green'),h('div',{class:'big-price'},money(m.unrealized_gross_usd)),...['entry_price','stop','target'].map((k,i)=>h('div',{class:'kv'},[h('span',['入场价','止损价','3R 目标'][i]),h('strong',fmt(v.position[k]))])),h('div',{class:'kv'},[h('span','初始价格风险 USD'),h('strong',fmt(m.risk_usd))])]:empty('当前空仓',f.status==='STOPPED'?'先启动观察程序。':historical?'正在查看历史日期。':'等待合格信号，不追补迟到交易。'),button('启动 / 参数设置',()=>settings.value=true,'primary wide'),button(f.paused?'继续新入场':'暂停新入场',()=>act(f.paused?'resume':'pause'),'wide',busy.value||!f.config)]),
 h('section',{class:'panel'},[title('下一步交易条件'),v.opening?h('div',{class:'split'},[h('div',[h('small','做多观察线'),h('strong',fmt(v.opening.high))]),h('div',[h('small','做空观察线'),h('strong',fmt(v.opening.low))])]):h('p','9:30–9:40 ET 建立开盘区间后显示观察线。'),h('p',{class:'muted'},'5 分钟收盘突破 → 新鲜报价模拟入场 → 固定止损与 3R。10:30 前确认，每天最多一笔。')]),
 h('section',{class:'panel'},[title('最近交易事件'),v.events.length?h('ol',{class:'timeline'},v.events.slice(-5).reverse().map(e=>h('li',[h('time',time(e.received_at_utc)),h('strong',kinds[e.kind]||e.kind),h('span',reasons[e.reason]||'')]))):h('p',{class:'muted'},'尚无信号或交易事件，行情到达后自动更新。')])]),h('section',{class:'panel'},[title('今日交易',[button('查看完整交易数据',()=>page.value='trades','text-button')]),tradeTable(v)]));
 if(page.value==='trades')panels.push(h('section',{class:'panel'},[title('完整模拟交易记录',[h('a',{href:`/download/${v.date||v.today}/trades`,class:'button'},'下载 CSV')]),h('p',{class:'muted'},'每合约 USD · 模拟报价成交 · 点击交易行查看图上买卖点'),tradeTable(v,true)]));
 if(viewTrade&&page.value==='desk')panels.push(h('section',{class:'panel'},[title('选中交易详情',[button('关闭详情',()=>selected.value=null,'text-button')]),h('div',{class:'detail-grid'},Object.entries({'合约':viewTrade.contract||'未记录','入场时间 ET':time(viewTrade.entry_time),'平仓时间 ET':time(viewTrade.exit_time),'退出原因':reasons[viewTrade.reason]||viewTrade.reason||'尚未退出','往返费用 USD':fmt(viewTrade.fee_usd),'单边滑点 tick':viewTrade.slippage_ticks??'未记录','净盈亏 USD':money(viewTrade.net_usd),'执行方式':'模拟报价代理'}).map(([k,value])=>h('div',[h('small',k),h('strong',String(value))])))]));
 if(page.value==='research')panels.push(h('section',{class:'panel'},[title('研究与每日总结',[pill('WEAK · 尚未证明 edge','amber')]),h('p','当前观察 ORB10 + 3R。时区、费用和成交模型尚未完成资格核验，单日盈亏不能决定止盈止损优化。'),h('div',{class:'strategy-list'},['ORB10 + 3R：已接入实时诊断','VWAP / Failed Breakout / Gap Fade：ES 尚未接入','Gamma：独立 SPY 研究，尚未映射到 ES'].map(t=>h('p',t))),v.report_available?h('a',{href:`/download/${v.date}/report`,class:'button'},'下载当日总结'):h('p',{class:'muted'},'当日总结将在现金收盘后生成。'),v.recommendation?h('div',{class:'notice'},[h('strong','当日建议'),h('span',v.recommendation)]):null,title('选择下一步优化方向'),h('div',{class:'choice-grid'},[['KEEP_FROZEN','保持冻结','继续收集完整日样本'],['QUALIFY_DATA_AND_COSTS','核验数据和费用','优先处理缺口、时区与成本'],['REGISTER_ENTRY_STUDY','研究入场延迟','另建版本，不改当前规则']].map(([id,label,description])=>button([h('strong',label),h('small',description)],()=>act('choose',{option:id,session_date:v.date}),'choice',busy.value))),h('p',{class:'muted'},v.latest_choice?`最近选择：${v.latest_choice}；当前策略未改动。`:'选择会保留记录，不会自动修改策略。')]));
 if(page.value==='data')panels.push(h('section',{class:'panel'},[title('数据质量与连接'),h('div',{class:'detail-grid'},Object.entries({'报价时间 ET':time(q.time),'接收时间 ET':time(q.received_time),'行情年龄':q.age_seconds==null?'未知':fmt(q.age_seconds,1)+' 秒','页面连接':connected.value?'已连接':'中断','估值资格':q.stale?'过期或尚无报价':'新鲜','完整分钟':v.bars.length,'权限检查时间 ET':time(s?.permissions.at_utc),'检查异常':errors[s?.probe_error]||s?.probe_error||'无'}).map(([k,value])=>h('div',[h('small',k),h('strong',String(value))]))),button(s?.probing?'正在检查…':'重新检查行情权限',()=>act('probe'),'primary',s?.probing||busy.value),h('div',{class:'permission-grid'},Object.entries(s?.permissions.products||{}).map(([p,val])=>h('div',[h('strong',p),h('p',`快照 ${val.snapshot?'可用':'不可用'} · 历史1m ${val.history?'可用':'不可用'}`)]))),h('p',{class:'muted'},'状态来自 OpenD 最近一次检查。休市不等于权限已通过。'),h('details',[h('summary','展开诊断日志'),h('pre',JSON.stringify({error:f.error,events:v.events},null,2))]),h('a',{href:`/download/${v.date||v.today}/events`,class:'button'},'下载事件日志')]));
 return h('div',{class:'shell'},[
 h('aside',{class:'sidebar'},[h('div',{class:'brand'},[h('span',{class:'brand-mark'},'↗'),h('div',[h('strong','交易研究'),h('small','ES / MES · FORWARD')])]),h('nav',[['desk','◈','交易驾驶台'],['trades','≋','交易数据'],['research','◇','研究与优化'],['data','◎','数据与连接']].map(([id,icon,name])=>button([h('span',icon),name],()=>page.value=id,page.value===id?'nav-active':''))),h('div',{class:'sidebar-note'},[pill('模拟观察','green'),h('p','无实盘下单'),h('small','ORB10 + 3R / 每日最多一笔')])]),
 h('main',[h('header',[h('div',[h('small',{class:'eyebrow'},'INTRADAY RESEARCH'),h('h1',{'desk':'交易驾驶台','trades':'交易数据','research':'研究与优化','data':'数据与连接'}[page.value])]),h('div',{class:'header-actions'},[h('label',{class:'date-picker'},['交易日 ',h('select',{value:date.value,onChange:e=>{date.value=e.target.value;selected.value=null;connect();}},[h('option',{value:''},'今天（纽约 ET）'),...v.dates.filter(d=>d!==v.today).map(d=>h('option',{value:d},d))])]),button('运行设置',()=>settings.value=true)])]),
 h('div',{class:`status-bar ${!connected.value?'disconnected':''}`},[pill(connected.value?'● 页面已连接':'● 页面连接中断',connected.value?'green':'amber'),h('span',states[f.status]||'连接中'),h('span',{OPEN:'现金时段',PREOPEN:'现金开盘前',CLOSED:'现金休市'}[v.market]||'等待状态'),h('span',q.age_seconds==null?'暂无报价':`行情年龄 ${fmt(q.age_seconds,0)} 秒`),pill(q.stale?'报价不可用于估值':'行情新鲜',q.stale?'amber':'green')]),
 (!gate||f.error)?h('div',{class:'notice'},[h('strong',f.error?'观察异常':'行情资格尚未通过'),h('span',errors[f.error]||'先检查 CME 报价与历史分钟权限，再启动观察。'),button('查看连接',()=>page.value='data','text-button')]):null,
 historical?h('div',{class:'notice'},`正在查看 ${v.date} 历史记录；当前持仓与浮盈仅在今天显示。`):null,
 message.value?h('div',{class:'notice',role:'status'},[h('span',message.value),button('关闭',()=>message.value='','text-button')]):null,
 h('div',{class:'stats'},stats.map(([label,value,note],i)=>h('section',{class:'stat'},[h('small',label),h('strong',{class:i===1&&m.realized_net_usd!=null?(m.realized_net_usd>=0?'positive':'negative'):''},value),h('span',note)]))),...panels,
 h('footer','诊断报价代理 · 费用为声明值 · 数据缺口会取消交易资格 · 页面推送每秒刷新，行情采集约每 3 秒一次')]),
 settings.value?h('div',{class:'overlay',onKeydown:e=>{if(e.key==='Escape')settings.value=false;if(e.key==='Tab'){const fields=[...e.currentTarget.querySelectorAll('button,input,select')].filter(el=>!el.disabled);const first=fields[0],last=fields.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}},[h('section',{class:'settings',role:'dialog','aria-modal':true,'aria-label':'运行参数设置'},[title('运行参数设置',[button('关闭',()=>settings.value=false,'text-button')]),h('p',{class:'muted'},'填写后冻结为本次运行参数。只启动模拟观察。'),h('form',{onSubmit:start},[field('品种','product',[['ES','ES'],['MES','MES']]),field('实际合约','contract',null,'text','选择实际月份合约，不使用主连。'),field('合约到期日','expires_on',null,'date'),field('接口时间时区','timezone',[['America/New_York','纽约（需核验）'],['America/Chicago','芝加哥（需核验）']]),field('每合约往返费用 USD','fee',null,'number','填写实际费用或明确假设，允许 0。'),field('单边滑点 tick','slip',null,'number'),h('button',{type:'submit',class:'primary wide',disabled:busy.value},'启动实时模拟观察')]),h('p',{class:'muted'},'保持电脑和 OpenD 在线。休市时等待现金开盘；暂停只阻止新入场。'),message.value?h('p',{role:'status',class:'negative'},message.value):null])]):null]);
 };
}}).mount('#app');
